import { defineConfig } from 'vite-plus';

export default defineConfig({
  resolve: {
    tsconfigPaths: true,
    alias: {
      '@microlabs/otel-cf-workers': new URL(
        'app/apex/__mocks__/@microlabs/otel-cf-workers.ts',
        import.meta.url,
      ).pathname,
      '@hono/otel': new URL('app/apex/__mocks__/@hono/otel.ts', import.meta.url).pathname,
    },
  },
  test: {
    coverage: {
      exclude: [
        '**/+types/**',
        '**/*.d.ts',
        '**/*.test.{ts,tsx}',
        '**/node_modules/**',
        '**/build/**',
        '**/dist/**',
        '**/__mocks__/**',
        '**/public/**',
        '**/*.css',
        '**/*.svg',
        '**/workers/**',
        '**/test-setup.ts',
        '**/locales/**',
        '**/zod.ts',
        '**/coverage/**',
        '**/.next/**',
        '**/.open-next/**',
        '**/next.config.ts',
        '**/open-next.config.ts',
        '**/app/apex/src/page-content.tsx',
        '**/com/apex/src/page-content.tsx',
        '**/org/apex/src/page-content.tsx',
        '**/net/apex/src/page-content.tsx',
        '**/app/jump/src/index.tsx',
        '**/com/jump/src/index.tsx',
        '**/org/jump/src/index.tsx',
        '**/shared/apex/html/health-page.ts',
        '**/shared/apex/middleware/rate-limit.ts',
        '**/shared/apex/routes/about.ts',
        '**/shared/apex/routes/root.ts',
        '**/shared/cloudflare/image.ts',
        '**/apex/src/root-redirect.ts',
        '**/apex/src/footer.tsx',
        '**/apex/src/app.tsx',
        '**/apex/src/index.tsx',
        '**/apex/src/otel.ts',
        '**/apex/src/renderer.tsx',
        '**/apex/html/index.ts',
        '**/apex/middleware/index.ts',
        '**/apex/routes/index.ts',
        '**/src/i18n/**',
        '**/src/app/**',
      ],
      include: ['**/*.{ts,tsx,js,jsx}'],
      provider: 'v8',
      reporter: ['text', 'text-summary', 'html'],
      thresholds: {
        branches: 100,
        functions: 100,
        lines: 100,
        statements: 100,
      },
    },
    deps: {
      interopDefault: true,
    },
    environment: 'happy-dom',
    globals: true,
    include: [
      'app/**/*.test.{ts,tsx}',
      'com/**/*.test.{ts,tsx}',
      'org/**/*.test.{ts,tsx}',
      'net/**/*.test.{ts,tsx}',
      'shared/**/*.test.{ts,tsx}',
      'test/**/*.test.{ts,tsx}',
    ],
    setupFiles: ['./vitest.setup.ts'],
  },
});
